In [19]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf
import os
from tensorflow.keras.callbacks import ModelCheckpoint

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [20]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN"],1)

application_df

C:\Users\jorda\anaconda3\envs\PythonData\envs\mlenv\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [21]:
application_df.columns

Index(['NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE',
       'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS',
       'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

In [22]:
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [23]:
# Look at NAME value counts for binning
name_counts = application_df.NAME.value_counts()
# How many name counts are greater than 5?
name_counts[name_counts>5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [24]:
 #  How many name counts are less than or equal to 5?
name_counts[name_counts <= 5]

FLORIDA FAMILY CHILD CARE HOME ASSOCIATION INC                          5
GERONTOLOGICAL ADVANCED PRACTICE NURSES ASSOCIATION                     5
INTERNATIONL TRANSPLANT NURSES SOCIETY                                  5
NATIONAL ORGANIZATION FOR WOMEN INC                                     5
PTA HAWAII CONGRESS                                                     5
                                                                       ..
ST LOUIS SLAM WOMENS FOOTBALL                                           1
AIESEC ALUMNI IBEROAMERICA CORP                                         1
WEALLBLEEDRED ORG INC                                                   1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI    1
WATERHOUSE CHARITABLE TR                                                1
Name: NAME, Length: 19214, dtype: int64

In [25]:
# Determine which values to replace if counts are less than or equal to 5.
replace_application = list(name_counts[name_counts <= 5].index)

# Replace in dataframe
for app in replace_application:
    application_df.NAME = application_df.NAME.replace(app,"Other")
    
# Check to make sure binning was successful
application_df.NAME.value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [26]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df.APPLICATION_TYPE.value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [27]:
# Determine which values to replace if counts are less than ...?
replace_application = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in replace_application:
    application_df.APPLICATION_TYPE = application_df.APPLICATION_TYPE.replace(app,"Other")
    
# Check to make sure binning was successful
application_df.APPLICATION_TYPE.value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [28]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df.CLASSIFICATION.value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [29]:
# Determine which values to replace if counts are less than 1000
replace_class = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in replace_class:
    application_df.CLASSIFICATION = application_df.CLASSIFICATION.replace(cls,"Other")
    
# Check to make sure binning was successful
application_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [30]:
# Generate our categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()

In [31]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(application_df[application_cat]))

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(application_cat)
encode_df.head()

C:\Users\jorda\anaconda3\envs\PythonData\envs\mlenv\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,NAME_ALPHA PHI OMEGA,NAME_ALPHA PHI SIGMA,NAME_ALPHA PHI SIGMA INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [32]:
# Merge one-hot encoded features and drop the originals
application_df = application_df.merge(encode_df,left_index=True, right_index=True)
application_df = application_df.drop(application_cat,1)
application_df.head()

C:\Users\jorda\anaconda3\envs\PythonData\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [33]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

C:\Users\jorda\anaconda3\envs\PythonData\envs\mlenv\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until

In [34]:
 # Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [35]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  100
hidden_nodes_layer2 = 30
hidden_nodes_layer3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               39900

 dense_1 (Dense)             (None, 30)                3030

 dense_2 (Dense)             (None, 10)                310

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 43,251
Trainable params: 43,251
Non-trainable params: 0
_________________________________________________________________

In [36]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("challenge_checkpoints/",exist_ok=True)
checkpoint_path = "challenge_checkpoints/weights.{epoch:02d}.hdf5"

In [37]:
 # Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [38]:
# Create a callback that saves the model's weights every epoch
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path, 
    verbose=1, 
    save_weights_only=True,
    save_freq='epoch')

In [39]:
 # Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100, callbacks=[cp_callback])

Epoch 1/100
797/804 [============================>.] - ETA: 0s - loss: 0.4973 - accuracy: 0.7718
Epoch 1: saving model to challenge_checkpoints\weights.01.hdf5
804/804 [==============================] - 3s 1ms/step - loss: 0.4963 - accuracy: 0.7725
Epoch 2/100
800/804 [============================>.] - ETA: 0s - loss: 0.4449 - accuracy: 0.7933
Epoch 2: saving model to challenge_checkpoints\weights.02.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4449 - accuracy: 0.7933
Epoch 3/100
785/804 [============================>.] - ETA: 0s - loss: 0.4351 - accuracy: 0.7961
Epoch 3: saving model to challenge_checkpoints\weights.03.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.4354 - accuracy: 0.7958
Epoch 4/100
786/804 [============================>.] - ETA: 0s - loss: 0.4309 - accuracy: 0.7965
Epoch 4: saving model to challenge_checkpoints\weights.04.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.4310 - accuracy: 0.7964
Epoch 5/100
794/804 [============================>.] - ETA: 0s - loss: 0.4273 - accuracy: 0.7973
Epoch 5: saving model to challenge_checkpoints\weights.05.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.4272 - accuracy: 0.7973
Epoch 6/100
788/804 [============================>.] - ETA: 0s - loss: 0.4253 - accuracy: 0.7991
Epoch 6: saving model to challenge_checkpoints\weights.06.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4256 - accuracy: 0.7989
Epoch 7/100
774/804 [===========================>..] - ETA: 0s - loss: 0.4240 - accuracy: 0.7991
Epoch 7: saving model to challenge_checkpoints\weights.07.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4240 - accuracy: 0.7986
Epoch 8/100
795/804 [============================>.] - ETA: 0s - loss: 0.4225 - accuracy: 0.7990
Epoch 8: saving model to challenge_checkpoints\weights.08.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4228 - accuracy: 0.7990
Epoch 9/100
776/804 [===========================>..] - ETA: 0s - loss: 0.4208 - accuracy: 0.7990
Epoch 9: saving model to challenge_checkpoints\weights.09.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.4212 - accuracy: 0.7991
Epoch 10/100
784/804 [============================>.] - ETA: 0s - loss: 0.4216 - accuracy: 0.7987
Epoch 10: saving model to challenge_checkpoints\weights.10.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4209 - accuracy: 0.7994
Epoch 11/100
793/804 [============================>.] - ETA: 0s - loss: 0.4199 - accuracy: 0.8007
Epoch 11: saving model to challenge_checkpoints\weights.11.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4199 - accuracy: 0.8007
Epoch 12/100
795/804 [============================>.] - ETA: 0s - loss: 0.4182 - accuracy: 0.8015
Epoch 12: saving model to challenge_checkpoints\weights.12.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4189 - accuracy: 0.8010
Epoch 13/100
790/804 [============================>.] - ETA: 0s - loss: 0.4179 - accuracy: 0.8012
Epoch 13: saving model to challenge_checkpoints\weights.13.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4181 - accuracy: 0.8009
Epoch 14/100
777/804 [===========================>..] - ETA: 0s - loss: 0.4178 - accuracy: 0.8015
Epoch 14: saving model to challenge_checkpoints\weights.14.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4178 - accuracy: 0.8015
Epoch 15/100
800/804 [============================>.] - ETA: 0s - loss: 0.4169 - accuracy: 0.7996
Epoch 15: saving model to challenge_checkpoints\weights.15.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4171 - accuracy: 0.7996
Epoch 16/100
782/804 [============================>.] - ETA: 0s - loss: 0.4165 - accuracy: 0.8019
Epoch 16: saving model to challenge_checkpoints\weights.16.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4165 - accuracy: 0.8019
Epoch 17/100
801/804 [============================>.] - ETA: 0s - loss: 0.4163 - accuracy: 0.8018
Epoch 17: saving model to challenge_checkpoints\weights.17.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4163 - accuracy: 0.8018
Epoch 18/100
784/804 [============================>.] - ETA: 0s - loss: 0.4154 - accuracy: 0.8025
Epoch 18: saving model to challenge_checkpoints\weights.18.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4151 - accuracy: 0.8028
Epoch 19/100
785/804 [============================>.] - ETA: 0s - loss: 0.4153 - accuracy: 0.8010
Epoch 19: saving model to challenge_checkpoints\weights.19.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4149 - accuracy: 0.8014
Epoch 20/100
787/804 [============================>.] - ETA: 0s - loss: 0.4144 - accuracy: 0.8020
Epoch 20: saving model to challenge_checkpoints\weights.20.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4146 - accuracy: 0.8021
Epoch 21/100
800/804 [============================>.] - ETA: 0s - loss: 0.4137 - accuracy: 0.8033
Epoch 21: saving model to challenge_checkpoints\weights.21.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4138 - accuracy: 0.8032
Epoch 22/100
796/804 [============================>.] - ETA: 0s - loss: 0.4139 - accuracy: 0.8027
Epoch 22: saving model to challenge_checkpoints\weights.22.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4138 - accuracy: 0.8026
Epoch 23/100
792/804 [============================>.] - ETA: 0s - loss: 0.4139 - accuracy: 0.8024
Epoch 23: saving model to challenge_checkpoints\weights.23.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4132 - accuracy: 0.8027
Epoch 24/100
789/804 [============================>.] - ETA: 0s - loss: 0.4124 - accuracy: 0.8035
Epoch 24: saving model to challenge_checkpoints\weights.24.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4129 - accuracy: 0.8032
Epoch 25/100
789/804 [============================>.] - ETA: 0s - loss: 0.4129 - accuracy: 0.8020
Epoch 25: saving model to challenge_checkpoints\weights.25.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4126 - accuracy: 0.8022
Epoch 26/100
787/804 [============================>.] - ETA: 0s - loss: 0.4125 - accuracy: 0.8038
Epoch 26: saving model to challenge_checkpoints\weights.26.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4122 - accuracy: 0.8037
Epoch 27/100
802/804 [============================>.] - ETA: 0s - loss: 0.4117 - accuracy: 0.8040
Epoch 27: saving model to challenge_checkpoints\weights.27.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4115 - accuracy: 0.8042
Epoch 28/100
781/804 [============================>.] - ETA: 0s - loss: 0.4109 - accuracy: 0.8041
Epoch 28: saving model to challenge_checkpoints\weights.28.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4113 - accuracy: 0.8041
Epoch 29/100
797/804 [============================>.] - ETA: 0s - loss: 0.4115 - accuracy: 0.8041
Epoch 29: saving model to challenge_checkpoints\weights.29.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4111 - accuracy: 0.8042
Epoch 30/100
790/804 [============================>.] - ETA: 0s - loss: 0.4104 - accuracy: 0.8043
Epoch 30: saving model to challenge_checkpoints\weights.30.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4105 - accuracy: 0.8043
Epoch 31/100
799/804 [============================>.] - ETA: 0s - loss: 0.4103 - accuracy: 0.8051
Epoch 31: saving model to challenge_checkpoints\weights.31.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4103 - accuracy: 0.8050
Epoch 32/100
790/804 [============================>.] - ETA: 0s - loss: 0.4097 - accuracy: 0.8055
Epoch 32: saving model to challenge_checkpoints\weights.32.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4100 - accuracy: 0.8052
Epoch 33/100
794/804 [============================>.] - ETA: 0s - loss: 0.4097 - accuracy: 0.8044
Epoch 33: saving model to challenge_checkpoints\weights.33.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4095 - accuracy: 0.8047

Epoch 34/100
773/804 [===========================>..] - ETA: 0s - loss: 0.4096 - accuracy: 0.8044
Epoch 34: saving model to challenge_checkpoints\weights.34.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4090 - accuracy: 0.8051
Epoch 35/100
770/804 [===========================>..] - ETA: 0s - loss: 0.4102 - accuracy: 0.8037
Epoch 35: saving model to challenge_checkpoints\weights.35.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4095 - accuracy: 0.8041
Epoch 36/100
782/804 [============================>.] - ETA: 0s - loss: 0.4094 - accuracy: 0.8043
Epoch 36: saving model to challenge_checkpoints\weights.36.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4087 - accuracy: 0.8048
Epoch 37/100
779/804 [============================>.] - ETA: 0s - loss: 0.4084 - accuracy: 0.8043
Epoch 37: saving model to challenge_checkpoints\weights.37.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4085 - accuracy: 0.8042
Epoch 38/100
775/804 [===========================>..] - ETA: 0s - loss: 0.4088 - accuracy: 0.8048
Epoch 38: saving model to challenge_checkpoints\weights.38.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4083 - accuracy: 0.8052
Epoch 39/100
773/804 [===========================>..] - ETA: 0s - loss: 0.4077 - accuracy: 0.8054
Epoch 39: saving model to challenge_checkpoints\weights.39.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4082 - accuracy: 0.8052
Epoch 40/100
767/804 [===========================>..] - ETA: 0s - loss: 0.4090 - accuracy: 0.8046
Epoch 40: saving model to challenge_checkpoints\weights.40.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4080 - accuracy: 0.8053
Epoch 41/100
776/804 [===========================>..] - ETA: 0s - loss: 0.4075 - accuracy: 0.8057
Epoch 41: saving model to challenge_checkpoints\weights.41.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4081 - accuracy: 0.8052
Epoch 42/100
785/804 [============================>.] - ETA: 0s - loss: 0.4069 - accuracy: 0.8058
Epoch 42: saving model to challenge_checkpoints\weights.42.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4074 - accuracy: 0.8057
Epoch 43/100
769/804 [===========================>..] - ETA: 0s - loss: 0.4066 - accuracy: 0.8061
Epoch 43: saving model to challenge_checkpoints\weights.43.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4071 - accuracy: 0.8054
Epoch 44/100
783/804 [============================>.] - ETA: 0s - loss: 0.4070 - accuracy: 0.8056
Epoch 44: saving model to challenge_checkpoints\weights.44.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4071 - accuracy: 0.8060
Epoch 45/100
775/804 [===========================>..] - ETA: 0s - loss: 0.4065 - accuracy: 0.8062
Epoch 45: saving model to challenge_checkpoints\weights.45.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4069 - accuracy: 0.8061
Epoch 46/100
790/804 [============================>.] - ETA: 0s - loss: 0.4070 - accuracy: 0.8054
Epoch 46: saving model to challenge_checkpoints\weights.46.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4062 - accuracy: 0.8059
Epoch 47/100
777/804 [===========================>..] - ETA: 0s - loss: 0.4063 - accuracy: 0.8059
Epoch 47: saving model to challenge_checkpoints\weights.47.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4063 - accuracy: 0.8059
Epoch 48/100
782/804 [============================>.] - ETA: 0s - loss: 0.4064 - accuracy: 0.8066
Epoch 48: saving model to challenge_checkpoints\weights.48.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4063 - accuracy: 0.8068
Epoch 49/100
779/804 [============================>.] - ETA: 0s - loss: 0.4061 - accuracy: 0.8058
Epoch 49: saving model to challenge_checkpoints\weights.49.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4060 - accuracy: 0.8060
Epoch 50/100
784/804 [============================>.] - ETA: 0s - loss: 0.4052 - accuracy: 0.8052
Epoch 50: saving model to challenge_checkpoints\weights.50.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4057 - accuracy: 0.8057
Epoch 51/100
803/804 [============================>.] - ETA: 0s - loss: 0.4054 - accuracy: 0.8064
Epoch 51: saving model to challenge_checkpoints\weights.51.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4054 - accuracy: 0.8065
Epoch 52/100
786/804 [============================>.] - ETA: 0s - loss: 0.4041 - accuracy: 0.8055
Epoch 52: saving model to challenge_checkpoints\weights.52.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4049 - accuracy: 0.8052
Epoch 53/100
781/804 [============================>.] - ETA: 0s - loss: 0.4052 - accuracy: 0.8066
Epoch 53: saving model to challenge_checkpoints\weights.53.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4052 - accuracy: 0.8064
Epoch 54/100
784/804 [============================>.] - ETA: 0s - loss: 0.4044 - accuracy: 0.8074
Epoch 54: saving model to challenge_checkpoints\weights.54.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4053 - accuracy: 0.8070
Epoch 55/100
774/804 [===========================>..] - ETA: 0s - loss: 0.4049 - accuracy: 0.8061
Epoch 55: saving model to challenge_checkpoints\weights.55.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4048 - accuracy: 0.8062
Epoch 56/100
792/804 [============================>.] - ETA: 0s - loss: 0.4054 - accuracy: 0.8065
Epoch 56: saving model to challenge_checkpoints\weights.56.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4048 - accuracy: 0.8068
Epoch 57/100
775/804 [===========================>..] - ETA: 0s - loss: 0.4031 - accuracy: 0.8079
Epoch 57: saving model to challenge_checkpoints\weights.57.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4046 - accuracy: 0.8073
Epoch 58/100
778/804 [============================>.] - ETA: 0s - loss: 0.4044 - accuracy: 0.8072
Epoch 58: saving model to challenge_checkpoints\weights.58.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4046 - accuracy: 0.8069
Epoch 59/100
772/804 [===========================>..] - ETA: 0s - loss: 0.4035 - accuracy: 0.8063
Epoch 59: saving model to challenge_checkpoints\weights.59.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4045 - accuracy: 0.8064
Epoch 60/100
766/804 [===========================>..] - ETA: 0s - loss: 0.4038 - accuracy: 0.8070
Epoch 60: saving model to challenge_checkpoints\weights.60.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4044 - accuracy: 0.8066
Epoch 61/100
796/804 [============================>.] - ETA: 0s - loss: 0.4036 - accuracy: 0.8072
Epoch 61: saving model to challenge_checkpoints\weights.61.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4038 - accuracy: 0.8070
Epoch 62/100
803/804 [============================>.] - ETA: 0s - loss: 0.4045 - accuracy: 0.8071
Epoch 62: saving model to challenge_checkpoints\weights.62.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4045 - accuracy: 0.8072
Epoch 63/100
771/804 [===========================>..] - ETA: 0s - loss: 0.4042 - accuracy: 0.8078
Epoch 63: saving model to challenge_checkpoints\weights.63.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4039 - accuracy: 0.8078
Epoch 64/100
777/804 [===========================>..] - ETA: 0s - loss: 0.4030 - accuracy: 0.8074
Epoch 64: saving model to challenge_checkpoints\weights.64.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4035 - accuracy: 0.8068
Epoch 65/100
803/804 [============================>.] - ETA: 0s - loss: 0.4037 - accuracy: 0.8072
Epoch 65: saving model to challenge_checkpoints\weights.65.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4039 - accuracy: 0.8071
Epoch 66/100
767/804 [===========================>..] - ETA: 0s - loss: 0.4042 - accuracy: 0.8069
Epoch 66: saving model to challenge_checkpoints\weights.66.hdf5

804/804 [==============================] - 1s 1ms/step - loss: 0.4035 - accuracy: 0.8072
Epoch 67/100
777/804 [===========================>..] - ETA: 0s - loss: 0.4036 - accuracy: 0.8069
Epoch 67: saving model to challenge_checkpoints\weights.67.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4034 - accuracy: 0.8071
Epoch 68/100
799/804 [============================>.] - ETA: 0s - loss: 0.4032 - accuracy: 0.8067
Epoch 68: saving model to challenge_checkpoints\weights.68.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4032 - accuracy: 0.8068
Epoch 69/100
788/804 [============================>.] - ETA: 0s - loss: 0.4038 - accuracy: 0.8063
Epoch 69: saving model to challenge_checkpoints\weights.69.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4036 - accuracy: 0.8064
Epoch 70/100
773/804 [===========================>..] - ETA: 0s - loss: 0.4033 - accuracy: 0.8076
Epoch 70: saving model to challenge_checkpoints\weights.70.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4036 - accuracy: 0.8073
Epoch 71/100
783/804 [============================>.] - ETA: 0s - loss: 0.4032 - accuracy: 0.8078
Epoch 71: saving model to challenge_checkpoints\weights.71.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.4027 - accuracy: 0.8080
Epoch 72/100
791/804 [============================>.] - ETA: 0s - loss: 0.4037 - accuracy: 0.8063
Epoch 72: saving model to challenge_checkpoints\weights.72.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4028 - accuracy: 0.8069
Epoch 73/100
790/804 [============================>.] - ETA: 0s - loss: 0.4019 - accuracy: 0.8082
Epoch 73: saving model to challenge_checkpoints\weights.73.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4027 - accuracy: 0.8073
Epoch 74/100
787/804 [============================>.] - ETA: 0s - loss: 0.4025 - accuracy: 0.8082
Epoch 74: saving model to challenge_checkpoints\weights.74.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4028 - accuracy: 0.8078
Epoch 75/100
789/804 [============================>.] - ETA: 0s - loss: 0.4024 - accuracy: 0.8074
Epoch 75: saving model to challenge_checkpoints\weights.75.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4025 - accuracy: 0.8074
Epoch 76/100
797/804 [============================>.] - ETA: 0s - loss: 0.4025 - accuracy: 0.8080
Epoch 76: saving model to challenge_checkpoints\weights.76.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4025 - accuracy: 0.8078
Epoch 77/100
796/804 [============================>.] - ETA: 0s - loss: 0.4023 - accuracy: 0.8076
Epoch 77: saving model to challenge_checkpoints\weights.77.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4026 - accuracy: 0.8075
Epoch 78/100
803/804 [============================>.] - ETA: 0s - loss: 0.4025 - accuracy: 0.8072
Epoch 78: saving model to challenge_checkpoints\weights.78.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4023 - accuracy: 0.8073
Epoch 79/100
782/804 [============================>.] - ETA: 0s - loss: 0.4025 - accuracy: 0.8081
Epoch 79: saving model to challenge_checkpoints\weights.79.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4023 - accuracy: 0.8081
Epoch 80/100
802/804 [============================>.] - ETA: 0s - loss: 0.4024 - accuracy: 0.8076
Epoch 80: saving model to challenge_checkpoints\weights.80.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8078
Epoch 81/100
798/804 [============================>.] - ETA: 0s - loss: 0.4023 - accuracy: 0.8073
Epoch 81: saving model to challenge_checkpoints\weights.81.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4020 - accuracy: 0.8075
Epoch 82/100
789/804 [============================>.] - ETA: 0s - loss: 0.4026 - accuracy: 0.8075
Epoch 82: saving model to challenge_checkpoints\weights.82.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4021 - accuracy: 0.8079
Epoch 83/100
764/804 [===========================>..] - ETA: 0s - loss: 0.4020 - accuracy: 0.8073
Epoch 83: saving model to challenge_checkpoints\weights.83.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4018 - accuracy: 0.8075
Epoch 84/100
795/804 [============================>.] - ETA: 0s - loss: 0.4020 - accuracy: 0.8078
Epoch 84: saving model to challenge_checkpoints\weights.84.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4017 - accuracy: 0.8079
Epoch 85/100
790/804 [============================>.] - ETA: 0s - loss: 0.4027 - accuracy: 0.8068
Epoch 85: saving model to challenge_checkpoints\weights.85.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8072
Epoch 86/100
791/804 [============================>.] - ETA: 0s - loss: 0.4018 - accuracy: 0.8078
Epoch 86: saving model to challenge_checkpoints\weights.86.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4019 - accuracy: 0.8076
Epoch 87/100
799/804 [============================>.] - ETA: 0s - loss: 0.4018 - accuracy: 0.8073
Epoch 87: saving model to challenge_checkpoints\weights.87.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4023 - accuracy: 0.8070
Epoch 88/100
792/804 [============================>.] - ETA: 0s - loss: 0.4020 - accuracy: 0.8083
Epoch 88: saving model to challenge_checkpoints\weights.88.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4021 - accuracy: 0.8083
Epoch 89/100
781/804 [============================>.] - ETA: 0s - loss: 0.4027 - accuracy: 0.8065
Epoch 89: saving model to challenge_checkpoints\weights.89.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4019 - accuracy: 0.8071
Epoch 90/100
786/804 [============================>.] - ETA: 0s - loss: 0.4021 - accuracy: 0.8074
Epoch 90: saving model to challenge_checkpoints\weights.90.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4020 - accuracy: 0.8078
Epoch 91/100
765/804 [===========================>..] - ETA: 0s - loss: 0.4024 - accuracy: 0.8080
Epoch 91: saving model to challenge_checkpoints\weights.91.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4015 - accuracy: 0.8082
Epoch 92/100
796/804 [============================>.] - ETA: 0s - loss: 0.4017 - accuracy: 0.8073
Epoch 92: saving model to challenge_checkpoints\weights.92.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4020 - accuracy: 0.8072
Epoch 93/100
796/804 [============================>.] - ETA: 0s - loss: 0.4014 - accuracy: 0.8082
Epoch 93: saving model to challenge_checkpoints\weights.93.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4012 - accuracy: 0.8084
Epoch 94/100
771/804 [===========================>..] - ETA: 0s - loss: 0.4016 - accuracy: 0.8093
Epoch 94: saving model to challenge_checkpoints\weights.94.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4016 - accuracy: 0.8088
Epoch 95/100
789/804 [============================>.] - ETA: 0s - loss: 0.4014 - accuracy: 0.8079
Epoch 95: saving model to challenge_checkpoints\weights.95.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4014 - accuracy: 0.8078
Epoch 96/100
768/804 [===========================>..] - ETA: 0s - loss: 0.4020 - accuracy: 0.8085
Epoch 96: saving model to challenge_checkpoints\weights.96.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4015 - accuracy: 0.8084
Epoch 97/100
799/804 [============================>.] - ETA: 0s - loss: 0.4011 - accuracy: 0.8085
Epoch 97: saving model to challenge_checkpoints\weights.97.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4012 - accuracy: 0.8084
Epoch 98/100
804/804 [==============================] - ETA: 0s - loss: 0.4015 - accuracy: 0.8085
Epoch 98: saving model to challenge_checkpoints\weights.98.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4015 - accuracy: 0.8085
Epoch 99/100

769/804 [===========================>..] - ETA: 0s - loss: 0.4009 - accuracy: 0.8078
Epoch 99: saving model to challenge_checkpoints\weights.99.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4014 - accuracy: 0.8075
Epoch 100/100
771/804 [===========================>..] - ETA: 0s - loss: 0.4007 - accuracy: 0.8083
Epoch 100: saving model to challenge_checkpoints\weights.100.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.4011 - accuracy: 0.8084

In [40]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4496 - accuracy: 0.7887 - 378ms/epoch - 1ms/step
Loss: 0.4495985507965088, Accuracy: 0.788688063621521

In [41]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")